// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/terra-project/core/x/market/internal/types/
// ALIASGEN: github.com/terra-project/core/x/market/internal/keeper/
package market

import (
	"github.com/terra-project/core/x/market/internal/keeper"
	"github.com/terra-project/core/x/market/internal/types"
)

const (
	DefaultCodespace       = types.DefaultCodespace
	CodeInvalidOfferCoin   = types.CodeInvalidOfferCoin
	CodeNoEffectivePrice   = types.CodeNoEffectivePrice
	CodeRecursiveSwap      = types.CodeRecursiveSwap
	EventSwap              = types.EventSwap
	AttributeKeyOffer      = types.AttributeKeyOffer
	AttributeKeyTrader     = types.AttributeKeyTrader
	AttributeKeySwapCoin   = types.AttributeKeySwapCoin
	AttributeKeySwapFee    = types.AttributeKeySwapFee
	AttributeValueCategory = types.AttributeValueCategory
	ModuleName             = types.ModuleName
	StoreKey               = types.StoreKey
	RouterKey              = types.RouterKey
	QuerierRoute           = types.QuerierRoute
	DefaultParamspace      = types.DefaultParamspace
	QuerySwap              = types.QuerySwap
	QueryTerraPoolDelta    = types.QueryTerraPoolDelta
	QueryParameters        = types.QueryParameters
)

var (
	// functions aliases
	RegisterCodec       = types.RegisterCodec
	ErrNoEffectivePrice = types.ErrNoEffectivePrice
	ErrInvalidOfferCoin = types.ErrInvalidOfferCoin
	ErrRecursiveSwap    = types.ErrRecursiveSwap
	NewGenesisState     = types.NewGenesisState
	DefaultGenesisState = types.DefaultGenesisState
	ValidateGenesis     = types.ValidateGenesis
	NewMsgSwap          = types.NewMsgSwap
	DefaultParams       = types.DefaultParams
	NewQuerySwapParams  = types.NewQuerySwapParams
	NewKeeper           = keeper.NewKeeper
	ParamKeyTable       = keeper.ParamKeyTable
	NewQuerier          = keeper.NewQuerier

	// variable aliases
	ModuleCdc                       = types.ModuleCdc
	TerraPoolDeltaKey               = types.TerraPoolDeltaKey
	ParamStoreKeyBasePool           = types.ParamStoreKeyBasePool
	ParamStoreKeyPoolRecoveryPeriod = types.ParamStoreKeyPoolRecoveryPeriod
	ParamStoreKeyMinStabilitySpread = types.ParamStoreKeyMinStabilitySpread
	DefaultBasePool                 = types.DefaultBasePool
	DefaultPoolRecoveryPeriod       = types.DefaultPoolRecoveryPeriod
	DefaultMinStabilitySpread       = types.DefaultMinStabilitySpread
)

type (
	SupplyKeeper    = types.SupplyKeeper
	OracleKeeper    = types.OracleKeeper
	GenesisState    = types.GenesisState
	MsgSwap         = types.MsgSwap
	Params          = types.Params
	QuerySwapParams = types.QuerySwapParams
	TobinTax        = types.TobinTax
	TobinTaxList    = types.TobinTaxList
	Keeper          = keeper.Keeper
)
